name: Disable Mod and Deploy with WPPusher

on:
  push:
    branches:
      - main  # Replace with your deployment branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Disable the Mod
      - name: Disable Mod
        run: |
          curl -X GET "${{ secrets.DISABLE_MOD_URL }}"
        env:
          DISABLE_MOD_URL: ${{ secrets.DISABLE_MOD_URL }}

      # Step 3: Wait for the Mod to Disable (Optional)
      - name: Wait for Mod to Disable
        run: sleep 10  # Adjust the duration based on your mod's disable time

      # Step 4: Trigger WPPusher Deployment
      - name: Trigger WPPusher Deployment
        run: |
          curl -X POST "${{ secrets.WPPUSHER_PAYLOAD_URL }}"
        env:
          WPPUSHER_PAYLOAD_URL: ${{ secrets.WPPUSHER_PAYLOAD_URL }}

      # Step 5: (Optional) Re-enable the Mod After Deployment
      # Uncomment and configure if needed
      # - name: Re-enable Mod
      #   run: |
      #     curl -X GET "https://jotun.games/ReEnableURL?key=YourKeyHere"

      # - name: Wait for Mod to Re-enable
      #   run: sleep 10  # Adjust as necessary
